apiVersion: apps/v1
kind: Deployment
metadata:
  name: novnc-deploy
  labels:
    app: novnc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: novnc
  template:
    metadata:
      labels:
        name: novnc
    spec:
      containers:
      - command: ["sh", "-c"]
        args:
        - ./utils/launch.sh 
        - --vnc 
        - localhost:5901
        image: khajan/novnc
        name: novnc-container
        ports:
            - containerPort: 6080
        resources:
          limits:
            cpu: "0.5"
            memory: 2Gi
          requests:
            cpu: "0.5"
            memory: 100Mi
      restartPolicy: Always